--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14/09/2016 09:16:25 p.m.
-- Server version: 5.5.5-10.1.10-MariaDB
-- Client version: 4.1
--


-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

-- 
-- Set default database
--
USE nodejs;

--
-- Definition for table tipomensaje
--
DROP TABLE IF EXISTS tipomensaje;
CREATE TABLE tipomensaje (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(10) NOT NULL,
  link VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 3
AVG_ROW_LENGTH = 8192
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table registros
--
DROP TABLE IF EXISTS registros;
CREATE TABLE registros (
  idRegistro INT(11) NOT NULL AUTO_INCREMENT,
  idImagen INT(11) NOT NULL,
  user_name VARCHAR(255) DEFAULT NULL,
  user_description VARCHAR(255) DEFAULT NULL,
  user_img VARCHAR(255) DEFAULT NULL,
  tiempo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (idRegistro),
  CONSTRAINT FK_registros_tipomensaje_id FOREIGN KEY (idImagen)
    REFERENCES tipomensaje(id) ON DELETE RESTRICT ON UPDATE CASCADE
)
ENGINE = INNODB
AUTO_INCREMENT = 35
AVG_ROW_LENGTH = 528
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table tipomensaje
--
INSERT INTO tipomensaje VALUES
(1, 'Alerta', 'http://cdns2.freepik.com/foto-gratis/senal-de-advertencia-de-imagenes-predisenadas_419554.jpg'),
(2, 'informacio', 'https://image.freepik.com/foto-gratis/icono-de-informacion-3_21010495.jpg');

-- 
-- Dumping data for table registros
--
INSERT INTO registros VALUES
(2, 1, 'ivan dice que', NULL, NULL, '2016-09-04 04:39:06'),
(3, 2, 'esto es una prueba', NULL, NULL, '2016-09-04 05:16:45'),
(4, 2, 'ivan', '', '', '2016-09-04 23:23:25'),
(6, 1, 'ivaneaeaea', '', '', '2016-09-04 23:24:26'),
(7, 2, 'la herramienta se encuentra momentaneamente en man', '', '', '2016-09-05 00:16:06'),
(8, 2, 'unaprueba', NULL, NULL, '2016-09-05 23:05:54'),
(9, 1, 'esto es otra prueba', NULL, NULL, '2016-09-05 23:40:29'),
(11, 2, 'holakease', NULL, NULL, '2016-09-05 23:42:12'),
(12, 2, 'hola soy ivan', NULL, NULL, '2016-09-05 23:49:49'),
(13, 1, '', NULL, NULL, '2016-09-05 23:49:52'),
(14, 1, 'asdasdasd', NULL, NULL, '2016-09-05 23:50:02'),
(15, 2, 'la herramienta se encuentra mo', NULL, NULL, '2016-09-05 23:51:22'),
(16, 2, 'holaaaaaaaaaaaaaaaaaaaa', NULL, NULL, '2016-09-05 23:53:54'),
(17, 2, 'mensaje para todos y todas', NULL, NULL, '2016-09-05 23:55:10'),
(18, 1, 'a', NULL, NULL, '2016-09-05 23:55:21'),
(19, 2, 'ads', NULL, NULL, '2016-09-05 23:55:24'),
(20, 2, 'holakease', NULL, NULL, '2016-09-06 00:05:30'),
(21, 1, 'aaaaaaaaaaaaaaaaaaaa', NULL, NULL, '2016-09-06 00:35:25'),
(22, 2, 'aaaa', NULL, NULL, '2016-09-06 00:54:40'),
(23, 1, '', NULL, NULL, '2016-09-06 00:58:14'),
(24, 2, '', NULL, NULL, '2016-09-06 00:58:16'),
(25, 2, '', NULL, NULL, '2016-09-06 00:58:16'),
(26, 1, 'holllaaaaaa', NULL, NULL, '2016-09-06 01:01:34'),
(27, 2, '', NULL, NULL, '2016-09-06 01:22:19'),
(28, 2, '', NULL, NULL, '2016-09-06 01:22:21'),
(29, 2, '', NULL, NULL, '2016-09-06 01:22:49'),
(30, 2, '', NULL, NULL, '2016-09-06 01:24:43'),
(31, 2, '', NULL, NULL, '2016-09-06 01:24:44'),
(32, 1, '', NULL, NULL, '2016-09-06 01:24:47'),
(33, 1, 'holakease', NULL, NULL, '2016-09-06 01:41:05'),
(34, 1, 'esto es un problema', NULL, NULL, '2016-09-06 01:53:40');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;